// Query keys, in one place so mutations can update every cache that shows the same thing.
export const K = {
  yo: ["auth", "yo"],
  sesiones: ["auth", "sesiones"],
  invitacion: (t) => ["auth", "invitacion", t],
  disponibilidad: (desde, dias) => ["publico", "disponibilidad", desde, dias],
  planesPublicos: ["publico", "planes"],
  estudio: ["publico", "estudio"],
  mi: ["mi"],
  profeClases: (desde, hasta) => ["profe", "clases", desde ?? "", hasta ?? ""],
  profeClase: (id) => ["profe", "clase", id],
  profeResumen: (mes) => ["profe", "resumen", mes],
  tablero: ["admin", "tablero"],
  novedades: ["admin", "novedades"],
  agenda: (desde, hasta) => ["admin", "agenda", desde, hasta],
  horario: ["admin", "horario"],
  clientas: (f) => ["admin", "clientas", f],
  segmentos: ["admin", "segmentos"],
  clienta: (id) => ["admin", "clienta", id],
  pagos: (mes) => ["admin", "pagos", mes],
  espera: ["admin", "espera"],
  equipo: ["admin", "equipo"],
  ajustes: ["admin", "ajustes"],
  planes: ["admin", "planes"],
  registro: ["admin", "registro"],
  salud: ["admin", "salud"],
  atribucion: (d, h) => ["admin", "atribucion", d, h],
  waEstado: ["admin", "wa", "estado"],
  waConversaciones: (filtro, q) => ["admin", "wa", "conversaciones", filtro, q],
  waConversacion: (id) => ["admin", "wa", "conversacion", id],
  waPlantillas: ["admin", "wa", "plantillas"],
};
